version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: importlib-metadata
    versions:
    - 3.10.0
    - 3.10.1
    - 3.4.0
    - 3.5.0
    - 3.6.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
    - 3.8.0
    - 3.8.1
    - 3.9.0
    - 3.9.1
    - 4.0.0
  - dependency-name: decorator
    versions:
    - 4.4.2
    - 5.0.0
    - 5.0.1
    - 5.0.2
    - 5.0.3
    - 5.0.4
    - 5.0.5
    - 5.0.6
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: datadog
    versions:
    - 0.39.0
    - 0.40.0
    - 0.40.1
  - dependency-name: more-itertools
    versions:
    - 8.6.0
  - dependency-name: zipp
    versions:
    - 3.4.0
