sudo: required
language: python
python: 3.6
services:
  - docker
env:
  - PIPENV_IGNORE_VIRTUALENVS=1
before_install:
  - docker build -t wpt-api .
install: skip
script:
  - docker ps -a
notifications:
  email: fte-ci@mozilla.com
