sudo: required
language: python
python: 3.6
env:
  - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install -r pipenv.txt
  - pipenv install --dev
script:
  - pipenv run flake8
notifications:
  email: fte-ci@mozilla.com
