sudo: required
language: python
python: 3.6
services:
  - docker
branches:
  only:
    - master
    - job-dsl
install:
  - pip install -r pipenv.txt
  - pipenv install --dev
  - pipenv check
jobs:
  include:
    - stage: Linting
      script:
        - pipenv run flake8
    - stage: Docker build
      script:
        - docker build -t wpt-api .
notifications:
email: fte-ci@mozilla.com
