sudo: required
language: python
python: 3.6
services:
  - docker
env:
  global:
  - PIPENV_IGNORE_VIRTUALENVS=1

script:
  - pipenv install
  - pipenv check
install:
  - pip install -r pipenv.txt
jobs:
  include:
    - stage: Linting
      script:
        - pipenv run flake8
    - stage: Docker build
      script: docker build -t wpt-api .
notifications:
email: fte-ci@mozilla.com
