sudo: required
language: python
python: 3.6
services:
  - docker
env:
  global:
  - PIPENV_IGNORE_VIRTUALENVS=1
branches:
  only:
    - master
    - job-dsl
install:
  - pip install -r pipenv.txt
  - pipenv install
  - pipenv check
jobs:
  include:
    - stage: Linting
      script:
        - flake8
    - stage: Docker build
      script:
        - docker build -t wpt-api .
notifications:
email: fte-ci@mozilla.com
