sudo: required
language: python
python: 3.6
services:
  - docker
env:
  global:
  - PIPENV_IGNORE_VIRTUALENVS=1
before_install:
  - pip install -r pipenv.txt
  - docker build -t wpt-api .
jobs:
  include:
    - stage: Linting
      script: flake8
    - stage: Docker build
      script: docker build -t wpt-api .
install: skip
notifications:
email: fte-ci@mozilla.com
