sudo: required
language: python
python: 3.7
dist: xenial
services:
  - docker
branches:
  only:
    - master
install:
  - pip install -r pipenv.txt
  - pipenv install --dev
jobs:
  include:
    - stage: Linting
      script:
        - pipenv run flake8
    - stage: Docker build
      script:
        - docker build -t wpt-api .
notifications:
  email: fte-ci@mozilla.com
